import React from "react";
import FollowersUser from "../FollowersUser/FollowersUser";
import "./Followers.css";

const Followers = () => {
  return (
    <>
      <div className="followersContainer">
        <h3>Followers</h3>
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
        <FollowersUser />
      </div>
    </>
  );
};

export default Followers;
